  itrs:
      build:
        context: .
        dockerfile: Dockerfile.ubuntu
      image: steve353/monitorlab-itrs:2.0
      hostname: b4abc4b146ad
      container_name: itrs
      ports:
        - 7039:7039
        - 7036:7036
      deploy:
        resources:
          limits:
            memory: 200M
          reservations:
            memory: 50M
      volumes:
        - ${PWD}/ITRSLic:/opt/itrs/licensedir